#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__))
require 'lib/rumour'

include Rumour

port = ARGV.shift.to_i
seed = ARGV.shift.to_i

daemon = Daemon.new(Address.new("0.0.0.0", port))
daemon.bootstrap(Address.new("127.0.0.1", seed))
daemon.start
loop do
  n = rand(1000)
  daemon.update("foo", {0=>n})
  sleep(1)
end