#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__))
require 'lib/rumour'

include Rumour

address = ARGV.shift
seed = ARGV.shift

conn = Connection.new(address)
conn.bootstrap(seed)
conn.start

id = rand(10)
i = 1
loop do
  conn.update("count", {id=>i})
  sleep(1)
  puts "COUNT: #{conn.lookup("count").values.inject(0){|a,b| a+b}}"
  i += 1
end