#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__))
require 'lib/rumour'

include Rumour

address = ARGV.shift
seed = ARGV.shift

daemon = Daemon.new(address)
daemon.bootstrap(seed)
daemon.start
id = rand(10)
i = 1
loop do
  daemon.update("count", {id=>i})
  sleep(1)
  puts "COUNT: #{daemon.lookup("count").values.inject(0){|a,b| a+b}}"
  i += 1
end