#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__))
require 'lib/vignette'

include Vignette

address = ARGV.shift
seed = ARGV.shift

conn = Connection.new(address)
conn.bootstrap(seed)
conn.start

loop do
  conn.update("hll", HyperLogLog.vector(rand))
  sleep(1)
  puts "COUNT: #{HyperLogLog.estimate(conn.lookup("hll"))}"
end
